// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/albedo_dart.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class AlbedoDartBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AlbedoDartBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AlbedoDartBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  albedo_result albedo_open(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Pointer<albedo_bucket_handle>> out_handle,
  ) {
    return albedo_result.fromValue(_albedo_open(path, out_handle));
  }

  late final _albedo_openPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<albedo_bucket_handle>>,
      )
    >
  >('albedo_open');
  late final _albedo_open =
      _albedo_openPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<albedo_bucket_handle>>,
            )
          >();

  albedo_result albedo_open_with_options(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Uint8> options_buffer,
    ffi.Pointer<ffi.Pointer<albedo_bucket_handle>> out_handle,
  ) {
    return albedo_result.fromValue(
      _albedo_open_with_options(path, options_buffer, out_handle),
    );
  }

  late final _albedo_open_with_optionsPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Pointer<albedo_bucket_handle>>,
      )
    >
  >('albedo_open_with_options');
  late final _albedo_open_with_options =
      _albedo_open_with_optionsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<albedo_bucket_handle>>,
            )
          >();

  albedo_result albedo_close(ffi.Pointer<albedo_bucket_handle> bucket) {
    return albedo_result.fromValue(_albedo_close(bucket));
  }

  late final _albedo_closePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_bucket_handle>)
    >
  >('albedo_close');
  late final _albedo_close =
      _albedo_closePtr
          .asFunction<int Function(ffi.Pointer<albedo_bucket_handle>)>();

  albedo_result albedo_insert(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> doc_buffer,
  ) {
    return albedo_result.fromValue(_albedo_insert(bucket, doc_buffer));
  }

  late final _albedo_insertPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
      )
    >
  >('albedo_insert');
  late final _albedo_insert =
      _albedo_insertPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
            )
          >();

  albedo_result albedo_transaction_begin(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Pointer<albedo_transaction_handle>> out_handle,
  ) {
    return albedo_result.fromValue(
      _albedo_transaction_begin(bucket, out_handle),
    );
  }

  late final _albedo_transaction_beginPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Pointer<albedo_transaction_handle>>,
      )
    >
  >('albedo_transaction_begin');
  late final _albedo_transaction_begin =
      _albedo_transaction_beginPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Pointer<albedo_transaction_handle>>,
            )
          >();

  albedo_result albedo_transaction_insert(
    ffi.Pointer<albedo_transaction_handle> tx,
    ffi.Pointer<ffi.Uint8> doc_buffer,
  ) {
    return albedo_result.fromValue(_albedo_transaction_insert(tx, doc_buffer));
  }

  late final _albedo_transaction_insertPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_transaction_handle>,
        ffi.Pointer<ffi.Uint8>,
      )
    >
  >('albedo_transaction_insert');
  late final _albedo_transaction_insert =
      _albedo_transaction_insertPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_transaction_handle>,
              ffi.Pointer<ffi.Uint8>,
            )
          >();

  albedo_result albedo_transaction_delete(
    ffi.Pointer<albedo_transaction_handle> tx,
    ffi.Pointer<ffi.Uint8> query_buffer,
    int query_len,
  ) {
    return albedo_result.fromValue(
      _albedo_transaction_delete(tx, query_buffer, query_len),
    );
  }

  late final _albedo_transaction_deletePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_transaction_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Uint16,
      )
    >
  >('albedo_transaction_delete');
  late final _albedo_transaction_delete =
      _albedo_transaction_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_transaction_handle>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  albedo_result albedo_transaction_update(
    ffi.Pointer<albedo_transaction_handle> tx,
    ffi.Pointer<ffi.Uint8> query_buffer,
    int query_len,
    ffi.Pointer<ffi.Uint8> program_buffer,
    int program_len,
    ffi.Pointer<ffi.Size> out_updated,
  ) {
    return albedo_result.fromValue(
      _albedo_transaction_update(
        tx,
        query_buffer,
        query_len,
        program_buffer,
        program_len,
        out_updated,
      ),
    );
  }

  late final _albedo_transaction_updatePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_transaction_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Uint16,
        ffi.Pointer<ffi.Uint8>,
        ffi.Uint16,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('albedo_transaction_update');
  late final _albedo_transaction_update =
      _albedo_transaction_updatePtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_transaction_handle>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Size>,
            )
          >();

  albedo_result albedo_transaction_transform(
    ffi.Pointer<albedo_transaction_handle> tx,
    ffi.Pointer<ffi.Uint8> query_buffer,
    ffi.Pointer<ffi.Pointer<albedo_transform_handle>> out_handle,
  ) {
    return albedo_result.fromValue(
      _albedo_transaction_transform(tx, query_buffer, out_handle),
    );
  }

  late final _albedo_transaction_transformPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_transaction_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Pointer<albedo_transform_handle>>,
      )
    >
  >('albedo_transaction_transform');
  late final _albedo_transaction_transform =
      _albedo_transaction_transformPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_transaction_handle>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<albedo_transform_handle>>,
            )
          >();

  albedo_result albedo_transaction_commit(
    ffi.Pointer<albedo_transaction_handle> tx,
  ) {
    return albedo_result.fromValue(_albedo_transaction_commit(tx));
  }

  late final _albedo_transaction_commitPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_transaction_handle>)
    >
  >('albedo_transaction_commit');
  late final _albedo_transaction_commit =
      _albedo_transaction_commitPtr
          .asFunction<int Function(ffi.Pointer<albedo_transaction_handle>)>();

  albedo_result albedo_transaction_rollback(
    ffi.Pointer<albedo_transaction_handle> tx,
  ) {
    return albedo_result.fromValue(_albedo_transaction_rollback(tx));
  }

  late final _albedo_transaction_rollbackPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_transaction_handle>)
    >
  >('albedo_transaction_rollback');
  late final _albedo_transaction_rollback =
      _albedo_transaction_rollbackPtr
          .asFunction<int Function(ffi.Pointer<albedo_transaction_handle>)>();

  albedo_result albedo_transaction_close(
    ffi.Pointer<albedo_transaction_handle> tx,
  ) {
    return albedo_result.fromValue(_albedo_transaction_close(tx));
  }

  late final _albedo_transaction_closePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_transaction_handle>)
    >
  >('albedo_transaction_close');
  late final _albedo_transaction_close =
      _albedo_transaction_closePtr
          .asFunction<int Function(ffi.Pointer<albedo_transaction_handle>)>();

  albedo_result albedo_ensure_index(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Char> path,
    int options_byte,
  ) {
    return albedo_result.fromValue(
      _albedo_ensure_index(bucket, path, options_byte),
    );
  }

  late final _albedo_ensure_indexPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Char>,
        ffi.Uint8,
      )
    >
  >('albedo_ensure_index');
  late final _albedo_ensure_index =
      _albedo_ensure_indexPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Char>,
              int,
            )
          >();

  albedo_result albedo_drop_index(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Char> path,
  ) {
    return albedo_result.fromValue(_albedo_drop_index(bucket, path));
  }

  late final _albedo_drop_indexPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('albedo_drop_index');
  late final _albedo_drop_index =
      _albedo_drop_indexPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  albedo_result albedo_list_indexes(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_doc,
  ) {
    return albedo_result.fromValue(_albedo_list_indexes(bucket, out_doc));
  }

  late final _albedo_list_indexesPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
      )
    >
  >('albedo_list_indexes');
  late final _albedo_list_indexes =
      _albedo_list_indexesPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  albedo_result albedo_delete(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> query_buffer,
    int query_len,
  ) {
    return albedo_result.fromValue(
      _albedo_delete(bucket, query_buffer, query_len),
    );
  }

  late final _albedo_deletePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Uint16,
      )
    >
  >('albedo_delete');
  late final _albedo_delete =
      _albedo_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  albedo_result albedo_update(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> query_buffer,
    int query_len,
    ffi.Pointer<ffi.Uint8> program_buffer,
    int program_len,
    ffi.Pointer<ffi.Size> out_updated,
  ) {
    return albedo_result.fromValue(
      _albedo_update(
        bucket,
        query_buffer,
        query_len,
        program_buffer,
        program_len,
        out_updated,
      ),
    );
  }

  late final _albedo_updatePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Uint16,
        ffi.Pointer<ffi.Uint8>,
        ffi.Uint16,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('albedo_update');
  late final _albedo_update =
      _albedo_updatePtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Size>,
            )
          >();

  albedo_result albedo_list(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> query_buffer,
    ffi.Pointer<ffi.Pointer<albedo_list_handle>> out_handle,
  ) {
    return albedo_result.fromValue(
      _albedo_list(bucket, query_buffer, out_handle),
    );
  }

  late final _albedo_listPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Pointer<albedo_list_handle>>,
      )
    >
  >('albedo_list');
  late final _albedo_list =
      _albedo_listPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<albedo_list_handle>>,
            )
          >();

  albedo_result albedo_list_cursor_export(
    ffi.Pointer<albedo_list_handle> handle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_cursor,
  ) {
    return albedo_result.fromValue(
      _albedo_list_cursor_export(handle, out_cursor),
    );
  }

  late final _albedo_list_cursor_exportPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_list_handle>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
      )
    >
  >('albedo_list_cursor_export');
  late final _albedo_list_cursor_export =
      _albedo_list_cursor_exportPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_list_handle>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  albedo_result albedo_data(
    ffi.Pointer<albedo_list_handle> handle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_doc,
  ) {
    return albedo_result.fromValue(_albedo_data(handle, out_doc));
  }

  late final _albedo_dataPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_list_handle>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
      )
    >
  >('albedo_data');
  late final _albedo_data =
      _albedo_dataPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_list_handle>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  albedo_result albedo_next(ffi.Pointer<albedo_list_handle> handle) {
    return albedo_result.fromValue(_albedo_next(handle));
  }

  late final _albedo_nextPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_list_handle>)
    >
  >('albedo_next');
  late final _albedo_next =
      _albedo_nextPtr
          .asFunction<int Function(ffi.Pointer<albedo_list_handle>)>();

  albedo_result albedo_close_iterator(ffi.Pointer<albedo_list_handle> handle) {
    return albedo_result.fromValue(_albedo_close_iterator(handle));
  }

  late final _albedo_close_iteratorPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_list_handle>)
    >
  >('albedo_close_iterator');
  late final _albedo_close_iterator =
      _albedo_close_iteratorPtr
          .asFunction<int Function(ffi.Pointer<albedo_list_handle>)>();

  albedo_result albedo_checkpoint(ffi.Pointer<albedo_bucket_handle> bucket) {
    return albedo_result.fromValue(_albedo_checkpoint(bucket));
  }

  late final _albedo_checkpointPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_bucket_handle>)
    >
  >('albedo_checkpoint');
  late final _albedo_checkpoint =
      _albedo_checkpointPtr
          .asFunction<int Function(ffi.Pointer<albedo_bucket_handle>)>();

  albedo_result albedo_vacuum(ffi.Pointer<albedo_bucket_handle> bucket) {
    return albedo_result.fromValue(_albedo_vacuum(bucket));
  }

  late final _albedo_vacuumPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_bucket_handle>)
    >
  >('albedo_vacuum');
  late final _albedo_vacuum =
      _albedo_vacuumPtr
          .asFunction<int Function(ffi.Pointer<albedo_bucket_handle>)>();

  albedo_result albedo_flush(ffi.Pointer<albedo_bucket_handle> bucket) {
    return albedo_result.fromValue(_albedo_flush(bucket));
  }

  late final _albedo_flushPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_bucket_handle>)
    >
  >('albedo_flush');
  late final _albedo_flush =
      _albedo_flushPtr
          .asFunction<int Function(ffi.Pointer<albedo_bucket_handle>)>();

  albedo_result albedo_transform(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> query_buffer,
    ffi.Pointer<ffi.Pointer<albedo_transform_handle>> out_handle,
  ) {
    return albedo_result.fromValue(
      _albedo_transform(bucket, query_buffer, out_handle),
    );
  }

  late final _albedo_transformPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Pointer<albedo_transform_handle>>,
      )
    >
  >('albedo_transform');
  late final _albedo_transform =
      _albedo_transformPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<albedo_transform_handle>>,
            )
          >();

  albedo_result albedo_transform_data(
    ffi.Pointer<albedo_transform_handle> handle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_doc,
  ) {
    return albedo_result.fromValue(_albedo_transform_data(handle, out_doc));
  }

  late final _albedo_transform_dataPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_transform_handle>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
      )
    >
  >('albedo_transform_data');
  late final _albedo_transform_data =
      _albedo_transform_dataPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_transform_handle>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  albedo_result albedo_transform_apply(
    ffi.Pointer<albedo_transform_handle> handle,
    ffi.Pointer<ffi.Uint8> transform_buffer,
  ) {
    return albedo_result.fromValue(
      _albedo_transform_apply(handle, transform_buffer),
    );
  }

  late final _albedo_transform_applyPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_transform_handle>,
        ffi.Pointer<ffi.Uint8>,
      )
    >
  >('albedo_transform_apply');
  late final _albedo_transform_apply =
      _albedo_transform_applyPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_transform_handle>,
              ffi.Pointer<ffi.Uint8>,
            )
          >();

  albedo_result albedo_transform_close(
    ffi.Pointer<albedo_transform_handle> handle,
  ) {
    return albedo_result.fromValue(_albedo_transform_close(handle));
  }

  late final _albedo_transform_closePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_transform_handle>)
    >
  >('albedo_transform_close');
  late final _albedo_transform_close =
      _albedo_transform_closePtr
          .asFunction<int Function(ffi.Pointer<albedo_transform_handle>)>();

  albedo_result albedo_replication_cursor(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Pointer<albedo_replication_cursor_handle>> out_cursor,
  ) {
    return albedo_result.fromValue(
      _albedo_replication_cursor(bucket, out_cursor),
    );
  }

  late final _albedo_replication_cursorPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Pointer<albedo_replication_cursor_handle>>,
      )
    >
  >('albedo_replication_cursor');
  late final _albedo_replication_cursor =
      _albedo_replication_cursorPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Pointer<albedo_replication_cursor_handle>>,
            )
          >();

  albedo_result albedo_replication_read(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<albedo_replication_cursor_handle> from,
    int max_bytes,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_batch,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return albedo_result.fromValue(
      _albedo_replication_read(bucket, from, max_bytes, out_batch, out_size),
    );
  }

  late final _albedo_replication_readPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<albedo_replication_cursor_handle>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('albedo_replication_read');
  late final _albedo_replication_read =
      _albedo_replication_readPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<albedo_replication_cursor_handle>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>,
            )
          >();

  albedo_result albedo_replication_apply(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> data,
    int data_size,
    ffi.Pointer<ffi.Pointer<albedo_replication_cursor_handle>> out_cursor,
  ) {
    return albedo_result.fromValue(
      _albedo_replication_apply(bucket, data, data_size, out_cursor),
    );
  }

  late final _albedo_replication_applyPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<albedo_replication_cursor_handle>>,
      )
    >
  >('albedo_replication_apply');
  late final _albedo_replication_apply =
      _albedo_replication_applyPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Pointer<albedo_replication_cursor_handle>>,
            )
          >();

  albedo_result albedo_replication_cursor_close(
    ffi.Pointer<albedo_replication_cursor_handle> cursor,
  ) {
    return albedo_result.fromValue(_albedo_replication_cursor_close(cursor));
  }

  late final _albedo_replication_cursor_closePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_replication_cursor_handle>)
    >
  >('albedo_replication_cursor_close');
  late final _albedo_replication_cursor_close =
      _albedo_replication_cursor_closePtr
          .asFunction<
            int Function(ffi.Pointer<albedo_replication_cursor_handle>)
          >();

  int albedo_bitsize() {
    return _albedo_bitsize();
  }

  late final _albedo_bitsizePtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('albedo_bitsize');
  late final _albedo_bitsize = _albedo_bitsizePtr.asFunction<int Function()>();

  int albedo_version() {
    return _albedo_version();
  }

  late final _albedo_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('albedo_version');
  late final _albedo_version = _albedo_versionPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Uint8> albedo_malloc(int size) {
    return _albedo_malloc(size);
  }

  late final _albedo_mallocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint8> Function(ffi.Size)>>(
        'albedo_malloc',
      );
  late final _albedo_malloc =
      _albedo_mallocPtr.asFunction<ffi.Pointer<ffi.Uint8> Function(int)>();

  void albedo_free(ffi.Pointer<ffi.Uint8> ptr, int size) {
    return _albedo_free(ptr, size);
  }

  late final _albedo_freePtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>
  >('albedo_free');
  late final _albedo_free =
      _albedo_freePtr.asFunction<void Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// ── Subscription (oplog change stream) ────────────────────────────────
  albedo_result albedo_subscribe(
    ffi.Pointer<albedo_bucket_handle> bucket,
    ffi.Pointer<ffi.Uint8> query_buffer,
    ffi.Pointer<ffi.Pointer<albedo_subscription_handle>> out_handle,
  ) {
    return albedo_result.fromValue(
      _albedo_subscribe(bucket, query_buffer, out_handle),
    );
  }

  late final _albedo_subscribePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_bucket_handle>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Pointer<albedo_subscription_handle>>,
      )
    >
  >('albedo_subscribe');
  late final _albedo_subscribe =
      _albedo_subscribePtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_bucket_handle>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<albedo_subscription_handle>>,
            )
          >();

  /// Poll for new change events.
  ///
  /// On ALBEDO_HAS_DATA, *out_doc points to a BSON document
  /// `{batch: [{seqno, op, doc_id, ts, doc?}, ...]}`.
  /// The memory is owned by the subscription and stays valid until the
  /// next albedo_subscribe_poll() or albedo_subscribe_close() call.
  ///
  /// Returns ALBEDO_EOS when idle, ALBEDO_OPLOG_GAP when the subscriber
  /// fell behind (must re-subscribe).
  albedo_result albedo_subscribe_poll(
    ffi.Pointer<albedo_subscription_handle> handle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_doc,
    int max_events,
  ) {
    return albedo_result.fromValue(
      _albedo_subscribe_poll(handle, out_doc, max_events),
    );
  }

  late final _albedo_subscribe_pollPtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<albedo_subscription_handle>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Uint32,
      )
    >
  >('albedo_subscribe_poll');
  late final _albedo_subscribe_poll =
      _albedo_subscribe_pollPtr
          .asFunction<
            int Function(
              ffi.Pointer<albedo_subscription_handle>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              int,
            )
          >();

  int albedo_subscribe_seqno(ffi.Pointer<albedo_subscription_handle> handle) {
    return _albedo_subscribe_seqno(handle);
  }

  late final _albedo_subscribe_seqnoPtr = _lookup<
    ffi.NativeFunction<
      ffi.Uint64 Function(ffi.Pointer<albedo_subscription_handle>)
    >
  >('albedo_subscribe_seqno');
  late final _albedo_subscribe_seqno =
      _albedo_subscribe_seqnoPtr
          .asFunction<int Function(ffi.Pointer<albedo_subscription_handle>)>();

  albedo_result albedo_subscribe_close(
    ffi.Pointer<albedo_subscription_handle> handle,
  ) {
    return albedo_result.fromValue(_albedo_subscribe_close(handle));
  }

  late final _albedo_subscribe_closePtr = _lookup<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<albedo_subscription_handle>)
    >
  >('albedo_subscribe_close');
  late final _albedo_subscribe_close =
      _albedo_subscribe_closePtr
          .asFunction<int Function(ffi.Pointer<albedo_subscription_handle>)>();
}

final class albedo_bucket_handle extends ffi.Opaque {}

final class albedo_list_handle extends ffi.Opaque {}

final class albedo_transform_handle extends ffi.Opaque {}

final class albedo_subscription_handle extends ffi.Opaque {}

final class albedo_transaction_handle extends ffi.Opaque {}

final class albedo_replication_cursor_handle extends ffi.Opaque {}

enum albedo_result {
  ALBEDO_OK(0),
  ALBEDO_ERROR(1),
  ALBEDO_HAS_DATA(2),
  ALBEDO_EOS(3),
  ALBEDO_OUT_OF_MEMORY(4),
  ALBEDO_FILE_NOT_FOUND(5),
  ALBEDO_NOT_FOUND(6),
  ALBEDO_INVALID_FORMAT(7),
  ALBEDO_DUPLICATE_KEY(8),
  ALBEDO_INVALID_CURSOR(9),
  ALBEDO_UNSUPPORTED_CURSOR_QUERY(10),
  ALBEDO_OPLOG_GAP(11),
  ALBEDO_REPLICATION_GAP(12),
  ALBEDO_TRANSACTION_ACTIVE(13),
  ALBEDO_INVALID_TRANSACTION(14),
  ALBEDO_TRANSACTION_BUSY(15);

  final int value;
  const albedo_result(this.value);

  static albedo_result fromValue(int value) => switch (value) {
    0 => ALBEDO_OK,
    1 => ALBEDO_ERROR,
    2 => ALBEDO_HAS_DATA,
    3 => ALBEDO_EOS,
    4 => ALBEDO_OUT_OF_MEMORY,
    5 => ALBEDO_FILE_NOT_FOUND,
    6 => ALBEDO_NOT_FOUND,
    7 => ALBEDO_INVALID_FORMAT,
    8 => ALBEDO_DUPLICATE_KEY,
    9 => ALBEDO_INVALID_CURSOR,
    10 => ALBEDO_UNSUPPORTED_CURSOR_QUERY,
    11 => ALBEDO_OPLOG_GAP,
    12 => ALBEDO_REPLICATION_GAP,
    13 => ALBEDO_TRANSACTION_ACTIVE,
    14 => ALBEDO_INVALID_TRANSACTION,
    15 => ALBEDO_TRANSACTION_BUSY,
    _ => throw ArgumentError("Unknown value for albedo_result: $value"),
  };
}

enum albedo_op_kind {
  ALBEDO_OP_INSERT(1),
  ALBEDO_OP_UPDATE(2),
  ALBEDO_OP_DELETE(3);

  final int value;
  const albedo_op_kind(this.value);

  static albedo_op_kind fromValue(int value) => switch (value) {
    1 => ALBEDO_OP_INSERT,
    2 => ALBEDO_OP_UPDATE,
    3 => ALBEDO_OP_DELETE,
    _ => throw ArgumentError("Unknown value for albedo_op_kind: $value"),
  };
}

enum albedo_payload_kind {
  ALBEDO_PAYLOAD_INLINE(0),
  ALBEDO_PAYLOAD_REF(1),
  ALBEDO_PAYLOAD_NONE(2);

  final int value;
  const albedo_payload_kind(this.value);

  static albedo_payload_kind fromValue(int value) => switch (value) {
    0 => ALBEDO_PAYLOAD_INLINE,
    1 => ALBEDO_PAYLOAD_REF,
    2 => ALBEDO_PAYLOAD_NONE,
    _ => throw ArgumentError("Unknown value for albedo_payload_kind: $value"),
  };
}
